
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Limitons à une seule version stable de Node.js
        node-version: [22-alpine]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Désactiver le cache temporairement
        # cache: 'npm'
    - name: Install dependencies
      run: pnpm install
    - name: Generate package-lock.json
      run: pnpm i --package-lock-only
    - name: Build
      run: pnpm run build --if-present
 